CURATED_WORDS = [
    "aberration", "abstruse", "acumen", "alacrity", "amalgamate", "ameliorate", 
    "anachronism", "anomalous", "antipathy", "arcane", "ascetic", "assuage", 
    "audacious", "austere", "avarice", "banal", "belligerent", "cacophony", 
    "capricious", "castigate", "catalyst", "caustic", "chicanery", "cogent", 
    "commensurate", "compendium", "complaisant", "conciliatory", "confound", 
    "connoisseur", "contention", "contentious", "contrite", "conundrum", 
    "craven", "credulous", "decorum", "deference", "delineate", "denigrate", 
    "deride", "derivative", "desiccate", "desultory", "diatribe", "didactic", 
    "dirge", "discern", "discordant", "discrete", "disparate", "dissemble", 
    "dissonance", "dogmatic", "ebullient", "eclectic", "efficacy", "elegy", 
    "elicit", "eloquent", "empirical", "emulate", "enervate", "engender", 
    "ephemeral", "equivocate", "erudite", "esoteric", "eulogy", "euphemism", 
    "exacerbate", "exculpate", "exigency", "extraneous", "facetious", "facilitate", 
    "fallacious", "fatuous", "fawning", "felicitous", "fervor", "flag", 
    "fledgling", "flout", "foment", "forestall", "frugality", "futile", 
    "gainsay", "garrulous", "goad", "gouge", "grandiloquent", "gregarious", 
    "guileless", "gullible", "halcyon", "harangue", "heterogeneous", "homogeneous", 
    "hyperbole", "iconoclast", "idolatry", "immutable", "impair", "impassive", 
    "impede", "impermeable", "imperturbable", "impervious", "implacable", 
    "implicit", "implode", "inadvertent", "inchoate", "incongruity", "inconsequential", 
    "incorporate", "indeterminate", "indigence", "indolent", "inert", "ingenuous", 
    "inherent", "innocuous", "insensible", "insinuate", "insipid", "insularity", 
    "intractable", "intransigence", "inundate", "inured", "invective", "irascible", 
    "irresolute", "itinerary", "laconic", "lassitude", "latent", "laud", 
    "lethargic", "levity", "log", "loquacious", "lucid", "luminous", 
    "magnanimity", "malingerer", "malleable", "maverick", "mendacious", "metamorphosis", 
    "meticulous", "misanthrope", "mitigate", "mollify", "morose", "mundane", 
    "negate", "neophyte", "obdurate", "obsequious", "obviate", "occlude", 
    "officious", "onerous", "opprobrium", "oscillate", "ostentatious", "paragon", 
    "partisan", "pathological", "paucity", "pedantic", "penchant", "penury", 
    "perennial", "perfidious", "perfunctory", "permeable", "pervasive", "phlegmatic", 
    "piety", "placate", "plasticity", "platitude", "plethora", "plummet", 
    "pragmatic", "precarious", "precipitate", "precursor", "presumptuous", "prevaricate", 
    "pristine", "probity", "problematic", "prodigal", "profound", "prohibitive", 
    "proliferate", "propensity", "propitiate", "propriety", "proscribe", "pungent", 
    "qualified", "quibble", "quiescent", "rarefied", "recalcitrant", "recant", 
    "recondite", "refractory", "refute", "relegate", "reproach", "reprobate", 
    "repudiate", "rescind", "resolution", "resolve", "reticent", "reverent", 
    "sage", "salubrious", "sanction", "satiate", "saturate", "savor", 
    "secrete", "shard", "skeptic", "solicitous", "soporific", "specious", 
    "spectrum", "sporadic", "stigma", "stint", "stipulate", "stolid", 
    "striated", "strut", "subpoena", "subside", "substantiate", "supersede", 
    "supposition", "tacit", "taciturn", "tangential", "tenuous", "tirade", 
    "torpor", "tortuous", "tractable", "transgression", "truculence", "vacillate", 
    "venerate", "veracious", "verbose", "viable", "viscous", "vituperative", 
    "volatile", "warranted", "wary", "welter", "whimsical", "zealot"
]
