"""Add 2FA columns

Revision ID: 0487da775262
Revises: b1a4ef088367
Create Date: 2026-08-20 19:47:15.177838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0487da775262'
down_revision: Union[str, Sequence[str], None] = 'b1a4ef088367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('two_factor_secret', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_two_factor_enabled')
    op.drop_column('user', 'two_factor_secret')
    # ### end Alembic commands ###
