"""add spiritual source and lesson models

Revision ID: 18121984d5cb
Revises: 13abf6cb202a
Create Date: 2026-08-09 13:46:15.975110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18121984d5cb'
down_revision: Union[str, Sequence[str], None] = '13abf6cb202a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiritual_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('verse', sa.Integer(), nullable=True),
    sa.Column('character', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('translation_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('license_or_rights_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spiritual_source_id'), 'spiritual_source', ['id'], unique=False)
    op.create_table('daily_spiritual_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('today_practice', sa.Text(), nullable=False),
    sa.Column('journal_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['spiritual_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_spiritual_lesson_id'), 'daily_spiritual_lesson', ['id'], unique=False)
    op.create_index(op.f('ix_daily_spiritual_lesson_lesson_date'), 'daily_spiritual_lesson', ['lesson_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_spiritual_lesson_lesson_date'), table_name='daily_spiritual_lesson')
    op.drop_index(op.f('ix_daily_spiritual_lesson_id'), table_name='daily_spiritual_lesson')
    op.drop_table('daily_spiritual_lesson')
    op.drop_index(op.f('ix_spiritual_source_id'), table_name='spiritual_source')
    op.drop_table('spiritual_source')
    # ### end Alembic commands ###
