"""add_daily_coding_lesson

Revision ID: 1a16cc92b2f7
Revises: 9541116e35a9
Create Date: 2026-08-15 21:48:50.023481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a16cc92b2f7'
down_revision: Union[str, Sequence[str], None] = '9541116e35a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_coding_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_coding_lesson_id'), 'daily_coding_lesson', ['id'], unique=False)
    op.create_index(op.f('ix_daily_coding_lesson_lesson_date'), 'daily_coding_lesson', ['lesson_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_coding_lesson_lesson_date'), table_name='daily_coding_lesson')
    op.drop_index(op.f('ix_daily_coding_lesson_id'), table_name='daily_coding_lesson')
    op.drop_table('daily_coding_lesson')
    # ### end Alembic commands ###
