"""Drop legacy tables

Revision ID: 1c6951c71e3b
Revises: 55fd3aa4f327
Create Date: 2026-08-15 22:10:34.678170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6951c71e3b'
down_revision: Union[str, Sequence[str], None] = '55fd3aa4f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_lesson_id'), table_name='health_lesson')
    op.drop_table('health_lesson')
    op.drop_index(op.f('ix_finance_lesson_id'), table_name='finance_lesson')
    op.drop_table('finance_lesson')
    op.drop_index(op.f('ix_spiritual_lesson_id'), table_name='spiritual_lesson')
    op.drop_table('spiritual_lesson')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiritual_lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('story', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('modern_example', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reflection', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('spiritual_lesson_pkey'))
    )
    op.create_index(op.f('ix_spiritual_lesson_id'), 'spiritual_lesson', ['id'], unique=False)
    op.create_table('finance_lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('problem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('example', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calculator_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('finance_lesson_pkey'))
    )
    op.create_index(op.f('ix_finance_lesson_id'), 'finance_lesson', ['id'], unique=False)
    op.create_table('health_lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('advice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scientific_evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_step', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('health_lesson_pkey'))
    )
    op.create_index(op.f('ix_health_lesson_id'), 'health_lesson', ['id'], unique=False)
    # ### end Alembic commands ###
