"""Add phone and dob to user

Revision ID: 26baeceb56aa
Revises: d01c61c518bf
Create Date: 2026-08-10 22:53:45.834427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26baeceb56aa'
down_revision: Union[str, Sequence[str], None] = 'd01c61c518bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
