"""Add dynamic stats to user

Revision ID: 2cbfc2d00b7d
Revises: 6d55b7b5853e
Create Date: 2026-08-07 22:16:43.712336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbfc2d00b7d'
down_revision: Union[str, Sequence[str], None] = '6d55b7b5853e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user', sa.Column('words_learned', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('quiz_correct_answers', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('quiz_total_answers', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('modules_completed', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_time_spent_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_time_spent_seconds')
    op.drop_column('user', 'modules_completed')
    op.drop_column('user', 'quiz_total_answers')
    op.drop_column('user', 'quiz_correct_answers')
    op.drop_column('user', 'words_learned')

    # ### end Alembic commands ###
