"""Add game_data to GameProgress

Revision ID: 37fc53de04a2
Revises: 63910e22c138
Create Date: 2026-08-14 21:16:50.154492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fc53de04a2'
down_revision: Union[str, Sequence[str], None] = '63910e22c138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_progress', sa.Column('game_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_progress', 'game_data')
    # ### end Alembic commands ###
