"""add daily finance lesson model

Revision ID: 41bcea07c59c
Revises: 18121984d5cb
Create Date: 2026-08-09 20:49:27.942439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bcea07c59c'
down_revision: Union[str, Sequence[str], None] = '18121984d5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_finance_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_date', 'country', name='uix_daily_finance_date_country')
    )
    op.create_index(op.f('ix_daily_finance_lesson_country'), 'daily_finance_lesson', ['country'], unique=False)
    op.create_index(op.f('ix_daily_finance_lesson_id'), 'daily_finance_lesson', ['id'], unique=False)
    op.create_index(op.f('ix_daily_finance_lesson_lesson_date'), 'daily_finance_lesson', ['lesson_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_finance_lesson_lesson_date'), table_name='daily_finance_lesson')
    op.drop_index(op.f('ix_daily_finance_lesson_id'), table_name='daily_finance_lesson')
    op.drop_index(op.f('ix_daily_finance_lesson_country'), table_name='daily_finance_lesson')
    op.drop_table('daily_finance_lesson')
    # ### end Alembic commands ###
