"""Add lessons models

Revision ID: 4cac82e51a69
Revises: 66d29a5e245c
Create Date: 2026-08-04 21:54:44.070883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cac82e51a69'
down_revision: Union[str, Sequence[str], None] = '66d29a5e245c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('calculator_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_lesson_id'), 'finance_lesson', ['id'], unique=False)
    op.create_table('health_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('scientific_evidence', sa.Text(), nullable=True),
    sa.Column('action_step', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_lesson_id'), 'health_lesson', ['id'], unique=False)
    op.create_table('spiritual_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(length=100), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('modern_example', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spiritual_lesson_id'), 'spiritual_lesson', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spiritual_lesson_id'), table_name='spiritual_lesson')
    op.drop_table('spiritual_lesson')
    op.drop_index(op.f('ix_health_lesson_id'), table_name='health_lesson')
    op.drop_table('health_lesson')
    op.drop_index(op.f('ix_finance_lesson_id'), table_name='finance_lesson')
    op.drop_table('finance_lesson')
    # ### end Alembic commands ###
