"""Add DailyHealthLesson

Revision ID: 4d7267f536a1
Revises: c96c2b61641c
Create Date: 2026-08-09 11:26:36.776229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d7267f536a1'
down_revision: Union[str, Sequence[str], None] = 'c96c2b61641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('health_facts', sa.JSON(), nullable=True),
    sa.Column('daily_activity', sa.JSON(), nullable=True),
    sa.Column('nutrition_tip', sa.JSON(), nullable=True),
    sa.Column('daily_habit', sa.JSON(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.String(length=100), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_health_lesson_id'), 'daily_health_lesson', ['id'], unique=False)
    op.create_index(op.f('ix_daily_health_lesson_lesson_date'), 'daily_health_lesson', ['lesson_date'], unique=True)
    op.drop_index(op.f('ix_news_article_category'), table_name='news_article')
    op.drop_index(op.f('ix_news_article_id'), table_name='news_article')
    op.drop_table('news_article')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_article_pkey'))
    )
    op.create_index(op.f('ix_news_article_id'), 'news_article', ['id'], unique=False)
    op.create_index(op.f('ix_news_article_category'), 'news_article', ['category'], unique=False)
    op.drop_index(op.f('ix_daily_health_lesson_lesson_date'), table_name='daily_health_lesson')
    op.drop_index(op.f('ix_daily_health_lesson_id'), table_name='daily_health_lesson')
    op.drop_table('daily_health_lesson')
    # ### end Alembic commands ###
