"""Add daily_quiz table

Revision ID: 55fd3aa4f327
Revises: 1a16cc92b2f7
Create Date: 2026-08-15 22:03:02.829131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fd3aa4f327'
down_revision: Union[str, Sequence[str], None] = '1a16cc92b2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.Date(), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quiz_id'), 'daily_quiz', ['id'], unique=False)
    op.create_index(op.f('ix_daily_quiz_lesson_date'), 'daily_quiz', ['lesson_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_quiz_lesson_date'), table_name='daily_quiz')
    op.drop_index(op.f('ix_daily_quiz_id'), table_name='daily_quiz')
    op.drop_table('daily_quiz')
    # ### end Alembic commands ###
