"""add game progress

Revision ID: 63910e22c138
Revises: 26baeceb56aa
Create Date: 2026-08-14 20:47:29.322767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63910e22c138'
down_revision: Union[str, Sequence[str], None] = '26baeceb56aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_progress_completion_date'), 'game_progress', ['completion_date'], unique=False)
    op.create_index(op.f('ix_game_progress_id'), 'game_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_progress_id'), table_name='game_progress')
    op.drop_index(op.f('ix_game_progress_completion_date'), table_name='game_progress')
    op.drop_table('game_progress')
    # ### end Alembic commands ###
