"""Add coding model

Revision ID: 66d29a5e245c
Revises: 29a374539af2
Create Date: 2026-08-04 21:53:02.358834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d29a5e245c'
down_revision: Union[str, Sequence[str], None] = '29a374539af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('time_complexity', sa.String(length=100), nullable=True),
    sa.Column('space_complexity', sa.String(length=100), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('java_solution', sa.Text(), nullable=True),
    sa.Column('python_solution', sa.Text(), nullable=True),
    sa.Column('cpp_solution', sa.Text(), nullable=True),
    sa.Column('javascript_solution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_problem_id'), 'coding_problem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_problem_id'), table_name='coding_problem')
    op.drop_table('coding_problem')
    # ### end Alembic commands ###
