"""Add KenKen puzzle

Revision ID: 8f1c56045cc4
Revises: 9a800d1f3700
Create Date: 2026-08-16 12:10:31.560898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1c56045cc4'
down_revision: Union[str, Sequence[str], None] = '9a800d1f3700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_ken_ken_puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_date', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('puzzle_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_date', 'size', name='uix_kenken_date_size')
    )
    op.create_index(op.f('ix_daily_ken_ken_puzzle_id'), 'daily_ken_ken_puzzle', ['id'], unique=False)
    op.create_index(op.f('ix_daily_ken_ken_puzzle_puzzle_date'), 'daily_ken_ken_puzzle', ['puzzle_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_ken_ken_puzzle_puzzle_date'), table_name='daily_ken_ken_puzzle')
    op.drop_index(op.f('ix_daily_ken_ken_puzzle_id'), table_name='daily_ken_ken_puzzle')
    op.drop_table('daily_ken_ken_puzzle')
    # ### end Alembic commands ###
