"""Add DailyOnThisDayEvent

Revision ID: 9541116e35a9
Revises: 37fc53de04a2
Create Date: 2026-08-15 13:05:55.502331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9541116e35a9'
down_revision: Union[str, Sequence[str], None] = '37fc53de04a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_on_this_day_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_on_this_day_event_date'), 'daily_on_this_day_event', ['date'], unique=True)
    op.create_index(op.f('ix_daily_on_this_day_event_id'), 'daily_on_this_day_event', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_on_this_day_event_id'), table_name='daily_on_this_day_event')
    op.drop_index(op.f('ix_daily_on_this_day_event_date'), table_name='daily_on_this_day_event')
    op.drop_table('daily_on_this_day_event')
    # ### end Alembic commands ###
