"""add_modules_explored_to_user

Revision ID: 9a800d1f3700
Revises: 1c6951c71e3b
Create Date: 2026-08-15 22:28:17.356943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a800d1f3700'
down_revision: Union[str, Sequence[str], None] = '1c6951c71e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modules_explored', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modules_explored')
    # ### end Alembic commands ###
