"""Add vocabulary model

Revision ID: a813e2ecb0ce
Revises: 480de3fdc4f3
Create Date: 2026-08-04 21:48:39.271353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a813e2ecb0ce'
down_revision: Union[str, Sequence[str], None] = '480de3fdc4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('pronunciation', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('antonyms', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('usage_tips', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_word_id'), 'vocabulary_word', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_word_word'), 'vocabulary_word', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_word_word'), table_name='vocabulary_word')
    op.drop_index(op.f('ix_vocabulary_word_id'), table_name='vocabulary_word')
    op.drop_table('vocabulary_word')
    # ### end Alembic commands ###
