"""update coding problem schema

Revision ID: c96c2b61641c
Revises: eaec84572d64
Create Date: 2026-08-08 21:40:42.206553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96c2b61641c'
down_revision: Union[str, Sequence[str], None] = 'eaec84572d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_problem', sa.Column('pattern', sa.String(length=100), nullable=True))
    op.add_column('coding_problem', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('coding_problem', sa.Column('approach', sa.Text(), nullable=True))
    op.add_column('coding_problem', sa.Column('explanation', sa.Text(), nullable=True))
    op.drop_column('coding_problem', 'ai_explanation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coding_problem', sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('coding_problem', 'explanation')
    op.drop_column('coding_problem', 'approach')
    op.drop_column('coding_problem', 'tags')
    op.drop_column('coding_problem', 'pattern')
    # ### end Alembic commands ###
