"""add savednews model

Revision ID: cd9eff15037f
Revises: 5f879b7aae20
Create Date: 2026-08-18 22:17:18.789298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9eff15037f'
down_revision: Union[str, Sequence[str], None] = '5f879b7aae20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_news_category'), 'saved_news', ['category'], unique=False)
    op.create_index(op.f('ix_saved_news_id'), 'saved_news', ['id'], unique=False)
    op.create_index(op.f('ix_saved_news_user_id'), 'saved_news', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_news_user_id'), table_name='saved_news')
    op.drop_index(op.f('ix_saved_news_id'), table_name='saved_news')
    op.drop_index(op.f('ix_saved_news_category'), table_name='saved_news')
    op.drop_table('saved_news')
    # ### end Alembic commands ###
