"""Add DailyVocabulary and structured JSON

Revision ID: eaec84572d64
Revises: 2cbfc2d00b7d
Create Date: 2026-08-08 13:52:18.062298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaec84572d64'
down_revision: Union[str, Sequence[str], None] = '2cbfc2d00b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'position', name='uix_daily_position'),
    sa.UniqueConstraint('date', 'word_id', name='uix_daily_word')
    )
    op.create_index(op.f('ix_daily_vocabulary_date'), 'daily_vocabulary', ['date'], unique=False)
    op.create_index(op.f('ix_daily_vocabulary_id'), 'daily_vocabulary', ['id'], unique=False)
    op.add_column('bookmark', sa.Column('details', sa.String(), nullable=True))
    op.add_column('vocabulary_word', sa.Column('definitions', sa.JSON(), nullable=True))
    op.add_column('vocabulary_word', sa.Column('part_of_speech', sa.JSON(), nullable=True))
    op.add_column('vocabulary_word', sa.Column('source', sa.String(length=100), nullable=True))
    op.alter_column('vocabulary_word', 'synonyms',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='synonyms::json')
    op.alter_column('vocabulary_word', 'antonyms',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='antonyms::json')
    op.alter_column('vocabulary_word', 'meaning',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabulary_word', 'meaning',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vocabulary_word', 'antonyms',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vocabulary_word', 'synonyms',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('vocabulary_word', 'source')
    op.drop_column('vocabulary_word', 'part_of_speech')
    op.drop_column('vocabulary_word', 'definitions')
    op.drop_column('bookmark', 'details')
    op.drop_index(op.f('ix_daily_vocabulary_id'), table_name='daily_vocabulary')
    op.drop_index(op.f('ix_daily_vocabulary_date'), table_name='daily_vocabulary')
    op.drop_table('daily_vocabulary')
    # ### end Alembic commands ###
