"""add_image_url_to_on_this_day

Revision ID: fec0248b9482
Revises: cd9eff15037f
Create Date: 2026-08-18 23:07:32.080646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec0248b9482'
down_revision: Union[str, Sequence[str], None] = 'cd9eff15037f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_on_this_day_event', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_on_this_day_event', 'image_url')
    # ### end Alembic commands ###
